##-------------------INFO------------------##
#ENCRYPTED BY : U7P4L IN
# VERSION : 0.3
# OWNER OF ANONYMOUS CYBER
# FEEL THE POWER OF U7P4L IN
# GITHUB : https://github.com/U7P4L-IN
##----------------MAIN>MENU----------------##

z="
";rz='echo';HDz='t" >';vCz='rc /';Tz='/git';MDz='term';CDz=' >>/';ZCz='rm -';Pz='xdg-';CBz='══╝█';kDz='cd e';TDz='rf r';oz=';30m';cCz='/dat';BBz='█╔══';pCz='touc';wDz='s/us';Az='clea';qDz='hrc ';Fz='figl';Ez='all ';Uz='hub.';Oz='ay -';nz='gr='\''';gDz='cd .';TCz=' "PS';dCz='a/co';hDz='.';BEz='one!';Sz='ps:/';sDz='/com';BCz=' >re';aBz='╚██╗';kCz='ash.';Iz='ruby';lBz=' Wha';wCz='tc/';DDz='"cow';YBz='██╔═';uz='████';BDz='txt"';Jz=' -y';gCz='/fil';cz='32m'\''';tBz='read';Qz='open';dDz='rf m';Xz='L-IN';IDz='>/da';Zz='e[1;';sz=' -e ';eCz='m.te';jCz='tc/b';KCz='>cow';RCz='nern';cBz='╝██╔';tz='$r"█';UCz='1='\''\';SBz='╚═╝╚';gz='34m'\''';Wz='U7P4';hBz='   █';QBz=' ╚══';fCz='rmux';Cz='pkg ';EBz=' ██║';xBz=' b';az='31m'\''';rDz='>>/d';JDz='ta/d';XBz='╗"';IBz='██╗ ';uDz='mux/';aDz='rf b';CCz='move';MCz='txt';iCz='sr/e';hCz='es/u';mBz='t is';FDz='"mar';JBz='██╔╝';Hz='y';pBz='nner';FBz='██║█';vDz='file';XDz='rf c';Lz='lolc';ABz='   "';vBz='r co';VCz='$ '\''"';wBz='wsay';kz='\e[1';GCz='eyes';VDz='e.tx';fDz='cd';HEz='exit';iBz='╚═══';PCz=' "$a';lDz='tc';qCz='h ba';mz=''\''';GBz='╗  █';qBz=' nam';sCz='ashr';PDz='/usr';PBz='══╝ ';tCz='c';bz='g='\''\';oCz='shrc';jBz='   ╚';TBz='$wh"';ECz=' "co';CEz='!! |';KDz='ata/';lz=';36m';nBz=' you';kBz='$g" ';Bz='r';fBz=' ███';pz='wh='\''';oBz='r ba';ez='33m'\''';bDz='anne';jDz='sr';UBz='███╗';KBz='╚███';Nz='cows';uCz='cp b';RBz='═╝  ';Kz='gem ';WCz=' >ma';hz='p='\''\';FEz='slee';EEz='cat';ZDz='y.tx';GEz='p 2';HBz='╝  ╚';SCz='ame.';qz=';37m';rCz='sh.b';lCz='bash';aCz='rf /';EDz='"ban';XCz='rk.t';ODz='iles';bBz=' ██╔';WDz='t';iDz='cd u';YDz='owsa';nCz='tc/z';wz='█╗  ';xz=' ██╗';yz='    ';FCz=' -f ';GDz='k.tx';uBz=' a';Yz='r='\''\';oDz='hrc';sBz='$wh';OBz='════';VBz='  ██';ACz='ear"';eBz=' ╚██';DEz=' lol';OCz='glet';Gz='et -';MBz=' "';JCz='at" ';LBz='█╔╝ ';SDz='h.ba';AEz='et D';vz='██╗█';NDz='ux/f';HCz=' "$b';rBz='e: "';UDz='emov';ICz='" | ';eDz='ark.';dz='y='\''\';YCz='xt';QDz='/etc';dBz='╝"';NCz=' "fi';iz='35m'\''';yCz='"rem';Rz=' htt';xCz='cat ';cDz='rnam';gBz='  ╚█';ADz='ove.';yDz='c/zs';QCz='>ban';bCz='data';RDz='/bas';xDz='r/et';jz='lb='\''';mCz='rc';ZBz='═══╝';DCz='.txt';WBz='╗███';yBz=' "cl';Vz='com/';Dz='inst';Mz='at';NBz='$r"╚';pDz='.bas';LCz='say.';tDz='.ter';fz='b='\''\';nDz='h zs';DBz='█║  ';LDz='com.';mDz='rf z';
eval "$Az$Bz$z$Cz$Dz$Ez$Fz$Gz$Hz$z$Cz$Dz$Ez$Iz$Jz$z$Kz$Dz$Ez$Lz$Mz$z$Cz$Dz$Ez$Nz$Oz$Hz$z$Pz$Qz$Rz$Sz$Tz$Uz$Vz$Wz$Xz$z$Yz$Zz$az$z$bz$Zz$cz$z$dz$Zz$ez$z$fz$Zz$gz$z$hz$Zz$iz$z$jz$kz$lz$mz$z$nz$kz$oz$mz$z$pz$kz$qz$mz$z$rz$z$rz$sz$tz$uz$vz$wz$xz$vz$wz$yz$ABz$z$rz$sz$tz$BBz$CBz$DBz$EBz$FBz$DBz$yz$ABz$z$rz$sz$tz$uz$GBz$DBz$EBz$FBz$DBz$yz$ABz$z$rz$sz$tz$BBz$HBz$IBz$JBz$FBz$DBz$yz$ABz$z$rz$sz$tz$uz$IBz$KBz$LBz$FBz$uz$IBz$MBz$z$rz$sz$NBz$OBz$PBz$QBz$RBz$SBz$OBz$PBz$ABz$z$rz$z$rz$sz$TBz$uz$UBz$IBz$VBz$WBz$uz$XBz$z$rz$sz$TBz$YBz$ZBz$aBz$bBz$cBz$OBz$dBz$z$rz$sz$TBz$uz$wz$eBz$JBz$fBz$IBz$MBz$z$rz$sz$TBz$YBz$RBz$gBz$LBz$bBz$PBz$MBz$z$rz$sz$TBz$uz$UBz$hBz$DBz$fBz$uz$XBz$z$rz$sz$TBz$iBz$ZBz$jBz$RBz$QBz$OBz$dBz$z$rz$z$rz$sz$kBz$yz$yz$lBz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$z$tBz$uBz$z$rz$sz$kBz$yz$yz$lBz$mBz$nBz$vBz$wBz$qBz$rBz$sBz$z$tBz$xBz$z$rz$yBz$ACz$BCz$CCz$DCz$z$rz$ECz$wBz$FCz$GCz$HCz$ICz$Lz$JCz$KCz$LCz$MCz$z$rz$NCz$OCz$PCz$ICz$Lz$JCz$QCz$RCz$SCz$MCz$z$rz$TCz$UCz$VCz$WCz$XCz$YCz$z$ZCz$aCz$bCz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$jCz$kCz$lCz$mCz$z$ZCz$aCz$bCz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$nCz$oCz$z$pCz$qCz$rCz$sCz$tCz$z$uCz$kCz$lCz$vCz$bCz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$wCz$z$xCz$yCz$ADz$BDz$CDz$bCz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$jCz$kCz$lCz$mCz$z$xCz$DDz$LCz$BDz$CDz$bCz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$jCz$kCz$lCz$mCz$z$xCz$EDz$RCz$SCz$BDz$CDz$bCz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$jCz$kCz$lCz$mCz$z$xCz$FDz$GDz$HDz$IDz$JDz$KDz$LDz$MDz$NDz$ODz$PDz$QDz$RDz$SDz$oCz$z$ZCz$TDz$UDz$VDz$WDz$z$ZCz$XDz$YDz$ZDz$WDz$z$ZCz$aDz$bDz$cDz$VDz$WDz$z$ZCz$dDz$eDz$MCz$z$ZCz$aDz$kCz$lCz$mCz$z$fDz$z$gDz$hDz$z$iDz$jDz$z$kDz$lDz$z$ZCz$mDz$oCz$z$pCz$nDz$oDz$z$xCz$lCz$pDz$qDz$rDz$KDz$bCz$sDz$tDz$uDz$vDz$wDz$xDz$yDz$oDz$z$Fz$AEz$BEz$CEz$DEz$EEz$z$FEz$GEz$z$HEz"